exclude:
  - Backend/2.4 QR Code Project/node_modules
  - Backend/4.0 EJS/node_modules
  - Backend/4.1 EJS Tags/node_modules
  - Backend/3.1 Express Server/node_modules
  - Backend/node_modules
  - node_modules
  - .git
